- name: Install ZSH
  apt: name=zsh
  tags: &tags_for_zsh_tasks [ 'install', 'productivity', 'dotfiles', 'zsh' ]
   
- name: Find the path to zsh
  command: which zsh
  register: zsh_path
  changed_when: false
  tags: *tags_for_zsh_tasks 

- name: Change shell to zsh
  become: true
  user:
    name: maca
    shell: "{{zsh_path.stdout}}" 
  tags: *tags_for_zsh_tasks

- name: Check that the somefile.conf exists
  stat:
    path: /home/maca/.oh-my-zsh
  register: oh_my_stats
  tags: *tags_for_zsh_tasks

- name: Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  tags: *tags_for_zsh_tasks
  when: oh_my_stats.stat.exists == False
  become_user: maca 

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags: *tags_for_zsh_tasks

- name: Add zsh-autosuggestions plugin to .zshrc
  lineinfile:
    path: /home/maca/.zshrc
    insertafter: '^plugins=\('
    line: 'plugins=(git zsh-autosuggestions)'
    backrefs: yes
    regexp: '^(plugins=\(.*\))$'
  tags: *tags_for_zsh_tasks

#- name: update zshrc
#  shell: sed -i 's/\(git\)/\(git zsh-autosuggestions\)/' ~/.zshrc
#  tags: *tags_for_zsh_tasks
