- name: Install ZSH
  become: true
  apt: name=zsh
  tags: &tags_for_zsh_tasks [ 'install', 'productivity', 'dotfiles', 'zsh' ]
   
- name: Find the path to zsh
  become: true
  command: which zsh
  register: zsh_path
  changed_when: false
  tags: *tags_for_zsh_tasks 

- name: Change shell to zsh
  become: true
  user:
    name: "{{ ansible_user_id  }}"
    shell: "{{zsh_path.stdout}}" 
  tags: *tags_for_zsh_tasks

- name: Check that the somefile.conf exists
  stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: oh_my_stats
  tags: *tags_for_zsh_tasks

- name: Oh-My-Zsh non-interactively
  shell: curl -L https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  tags: *tags_for_zsh_tasks
  when: oh_my_stats.stat.exists == False
  become_user: "{{ ansible_user_id  }}"

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags: *tags_for_zsh_tasks

- name: Add zsh-autosuggestions plugin to .zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    insertafter: '^plugins=\('
    line: 'plugins=(git zsh-autosuggestions)'
    backrefs: yes
    regexp: '^(plugins=\(.*\))$'
  tags: *tags_for_zsh_tasks

